### ISSUE TITLE
Doesn't recognize existing installation folder

### ISSUE THREAD

**Issue by pflky** [Samachiy/Qinti#6] opened 2024-04-26 16:41 UTC
Can setup a new installation, but cannot use existing installation. Tried the main folder of the existing installation and it simply doesn't detect anything and cannot proceed forward.

**Comment by redw04** [comment] 2024-04-26 19:57
Same issue. cannot proceed from selecting the installation folder. Have tried with Auto1111 both running and not running.

**Comment by Samachiy** [comment] 2024-04-26 21:10
Can I see the logs of the failed run? Those should be in:
Linux: ~/.local/share/godot/app_userdata/Qinti/logs
Windows: %APPDATA%\Godot\app_userdata\Qinti\logs

**Comment by Samachiy** [comment] 2024-04-26 21:20
A possible reason of why it fails may be that the way the program detects which backend is in use is by checking the git origin. If the repo is not cloned or if it's is cloned from a fork or the origin is set to another fork, it will fail to detect which backend it is.

If that is the case, then maybe I should add an option for manually selecting the type of backend and skipping the auto select.

The current origin can be seen using: git ls-remote --get-url origin

As of the latest release, only the following are recognized:
- https://github.com/vladmandic/automatic.git 
- https://github.com/AUTOMATIC1111/stable-diffusion-webui.git

**Comment by pflky** [comment] 2024-04-26 22:04
That may be the issue. I don't use gitclone to install, because I only manually upgrade. I don't think it needs to do any checks, it just needs to fall on the user to use the right folder location. So something that simply allows you to select your main install folder should suffice, rather than checking with git. Then from there an error can be presented if they selected the wrong folder and nothing is able to run as a result. So for example, the behavior could be to select any folder with no checks, then an error message that says something like "Stable Diffusion not found, install corrupted or wrong folder selected".  

Or the check can be for a specific file present instead, for example, the webui-user.bat file. If that is detected in the selected folder, than you can be assured you have the right folder. 

A lot of people don't use git to install A111, because auto updates can break things.

**Comment by Samachiy** [comment] 2024-04-26 22:34
I hadn't considered that, thanks.

Although, the problem is with that solution is that different backends like Automatic and Forge work a bit too different despite having almost the same files, so it is necessary to check which backend it is, but the file similarity still makes checks hard, for example, both have webui-user.bat file

Does your install has the Readme.md inside? If installs that don't use git clone still have the readme, then I could use that as fallback.

And, maybe then, if even that doesn't work, prompt the user to manually select the backend type

**Comment by redw04** [comment] 2024-04-26 22:37
I did use Git Clone to install however I also switched branches to a forked version. Thanks for the info that's definitely what's happening here. 

My install does have a readme.md, and here's the logs just in case that helps further 

Godot Engine v3.5.3.stable.official.6c814135b - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
Async. shader compilation: OFF
 
     - (14:00:31) Release version: 0.1.0
ERROR: Condition "ret == 0" is true. Returned: ERR_CANT_FORK
   at: execute (platform/windows/os_windows.cpp:2923) - Condition "ret == 0" is true. Returned: ERR_CANT_FORK
SCRIPT ERROR: Invalid operands 'String' and 'int' in operator '+'.
   at: make_file_executable (res://data_classes/pc_data.gdc:246) - Invalid operands 'String' and 'int' in operator '+'.
ERROR: Condition "ret == 0" is true. Returned: ERR_CANT_FORK
   at: execute (platform/windows/os_windows.cpp:2923) - Condition "ret == 0" is true. Returned: ERR_CANT_FORK
SCRIPT ERROR: Invalid operands 'String' and 'int' in operator '+'.
   at: make_file_executable (res://data_classes/pc_data.gdc:246) - Invalid operands 'String' and 'int' in operator '+'.
ERROR: Condition "ret == 0" is true. Returned: ERR_CANT_FORK
   at: execute (platform/windows/os_windows.cpp:2923) - Condition "ret == 0" is true. Returned: ERR_CANT_FORK
SCRIPT ERROR: Invalid operands 'String' and 'int' in operator '+'.
   at: make_file_executable (res://data_classes/pc_data.gdc:246) - Invalid operands 'String' and 'int' in operator '+'.
ERROR: Condition "ret == 0" is true. Returned: ERR_CANT_FORK
   at: execute (platform/windows/os_windows.cpp:2923) - Condition "ret == 0" is true. Returned: ERR_CANT_FORK
SCRIPT ERROR: Invalid operands 'String' and 'int' in operator '+'.
   at: make_file_executable (res://data_classes/pc_data.gdc:246) - Invalid operands 'String' and 'int' in operator '+'.
ERROR: Condition "ret == 0" is true. Returned: ERR_CANT_FORK
   at: execute (platform/windows/os_windows.cpp:2923) - Condition "ret == 0" is true. Returned: ERR_CANT_FORK
SCRIPT ERROR: Invalid operands 'String' and 'int' in operator '+'.
   at: make_file_executable (res://data_classes/pc_data.gdc:246) - Invalid operands 'String' and 'int' in operator '+'.
     - (14:00:31) Global file loaded. 
DEBUG: (14:00:32) Initial size set as: (1024, 713) with minimum size of (800, 715). 
     - (14:00:40) Loading server installed at: H:/SD/stable-diffusion-webui
ERROR: (14:00:40) The path 'H:/SD/stable-diffusion-webui' doesn't contain a valid repository
     - (14:00:43) Closing program
     - (14:00:43) Attempting Python process stop before shutdown
     - (14:00:43) Graceful game close achieved
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/self_list.h:108) - Condition "_first != nullptr" is true.
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/self_list.h:108) - Condition "_first != nullptr" is true.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: cleanup (core/object.cpp:2070) - ObjectDB instances leaked at exit (run with --verbose for details).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417) - Resources still in use at exit (run with --verbose for details).

**Comment by redw04** [comment] 2024-04-26 22:57
I just want to come back and confirm that switching branches back to the main branch did not fix this issue

EDIT: Also just tried a fresh install and it can't detect that either.

**Comment by atlcr** [comment] 2024-04-27 04:04
Same issue here. Cannot install into existing directory and trying to install a new one fails.
Logs attached.
[logs.zip](https://github.com/Samachiy/Qinti/files/15136985/logs.zip)

**Comment by Samachiy** [comment] 2024-04-27 21:30
Thanks for all the info and logs regarding the issue! :). I just published a new version that should take care of this problem.
This new version has a fallback check and if that doesn't work either, it will show a manual selector for the backend after the message of not a valid installation.

Any problem or recommendation that you have, please let me know here, the issue will remain open for a while.

**Comment by abellos** [comment] 2024-04-28 07:44
Tried now with the latest version, not working, program stay stuck on folder selection.
I have an exixting installation of A1111
Log say

Godot Engine v3.5.3.stable.official.6c814135b - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 4070/PCIe/SSE2
Async. shader compilation: OFF
 
     - (09:32:33) Release version: 0.1.1
ERROR: (09:32:33) Couldn't open file 'C:/Users/abellos/AppData/Roaming/Godot/app_userdata/Qinti/saves/global_save.dat'. File not found
DEBUG: (09:32:33) Initial size set as: (1024, 713) with minimum size of (800, 715). 
WARNING: (09:32:53) Error: 7. Failed to open file: D:/sd.webui/README.md
ERROR: File must be opened before use.
   at: eof_reached (core/bind/core_bind.cpp:2032) - Condition "!f" is true. Returned: false
ERROR: File must be opened before use.
   at: get_line (core/bind/core_bind.cpp:2113) - Condition "!f" is true. Returned: String()
ERROR: File must be opened before use.
   at: eof_reached (core/bind/core_bind.cpp:2032) - Condition "!f" is true. Returned: false
ERROR: File must be opened before use.
   at: get_line (core/bind/core_bind.cpp:2113) - Condition "!f" is true. Returned: String()
ERROR: File must be opened before use.
   at: eof_reached (core/bind/core_bind.cpp:2032) - Condition "!f" is true. Returned: false
ERROR: File must be opened before use.
   at: get_line (core/bind/core_bind.cpp:2113) - Condition "!f" is true. Returned: String()
ERROR: File must be opened before use.
   at: eof_reached (core/bind/core_bind.cpp:2032) - Condition "!f" is true. Returned: false
ERROR: File must be opened before use.
   at: get_line (core/bind/core_bind.cpp:2113) - Condition "!f" is true. Returned: String()
ERROR: File must be opened before use.
   at: eof_reached (core/bind/core_bind.cpp:2032) - Condition "!f" is true. Returned: false
ERROR: File must be opened before use.
   at: get_line (core/bind/core_bind.cpp:2113) - Condition "!f" is true. Returned: String()
ERROR: File must be opened before use.
   at: eof_reached (core/bind/core_bind.cpp:2032) - Condition "!f" is true. Returned: false
ERROR: File must be opened before use.
   at: get_line (core/bind/core_bind.cpp:2113) - Condition "!f" is true. Returned: String()
ERROR: File must be opened before use.

**Comment by Samachiy** [comment] 2024-04-28 09:46
Thanks for letting me know! 
Turns out the program was getting stuck if the file didn't exist, preventing some already working setups to start the program correctly. it is fixed now in a new release.

**Comment by abellos** [comment] 2024-04-28 14:27
I chose the wrong directory because is not clear. I set this directory D:\sd.webui where i have the run.bat (im on windows) instead of D:\sd.webui\webui where there is readme.md. You should write somewhere that the right directory is that where is located webui.bat / webui.py / webui.sh

**Comment by Samachiy** [comment] 2024-04-29 22:33
> You should write somewhere that the right directory is that where is located webui.bat / webui.py / webui.sh

That's a good point, thanks, I will implement it for the next non-patch release (since it's now more of a feature than a bug) as a message right besides the server type depending of the chosen backend once the server type input shows up for manual selection.

Since there hasn't been any more activity regarding the issue of the program failing to recognize the folder from a code standpoint, I will count the issue as solved

**Closed as completed by Samachiy** 2024-04-29 22:33 UTC
